# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=None)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('facebook', models.CharField(max_length=200)),
                ('whatsap', models.IntegerField()),
                ('remarques', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
